### ISSUE TITLE
Wrong attribute name for ssl passphrase

### ISSUE THREAD

**Issue by nocive** [cgravier/selfsigned_certificate#2]
You have a mismatch between what your documentation says and what the attribute file says, and what the code is expecting.

On both the attribute file and the documentation you mention an attribute node[:selfsigned_certificate][:passphrase] when in fact your code is expecting an attribute named node[:selfsigned_certificate][:sslpassphrase].

**Comment by cgravier** [comment]
Thanks for pointing this ! I fixed it to "sslpassphrase" in attribute and README, and left the code unchanged.

**Comment by nocive** [comment]
You're welcome! Thanks for fixing it so quickly :)
Keep up the good work

**Comment by cgravier** [comment]
You're welcome and thanks for your encouragement.
This was my first cookbook and as I am more experienced with cookbooks now, I would write it slightly differently.
However it does the job, and I'm using it as a dependency in several cookbooks.

**Comment by nocive** [comment]
I agree that probably some things could be improved, but then again this is only suitable for development environments. Besides, it serves it's purpose and I found it really useful, otherwise I would have to code my own.

We're using it at our company to generate a self signed cert for development vm's ;)

**Comment by cgravier** [comment]
I created it for the same purpose, after I was not able to find an existing one.
I'm glad you found it useful!
